PycharmProjects/CP_MOOP_PROG-main/products/urls.py
from django.urls import path, include
from django.contrib import admin
from products import views

urlpatterns = [
    # url(r'^landing123/', views.landing, name='landing'),
    path(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
]

PycharmProjects/CP_MOOP_PROG-main/test_project/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from landing import views


urlpatterns = [
                  path('', views.home, name='home'),

                  path('admin/', admin.site.urls),
    path('admin1/', include('myAdmin.urls')),
    path('', include('landing.urls')),
    path('', include('products.urls')),
    path('', include('orders.urls')),
    path('', include('users.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PycharmProjects/CP_MOOP_PROG-main/users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('accounts/signup', views.SignUpView.as_view(), name='signup'),
    path('accounts/', include('allauth.urls')),
]

PycharmProjects/CP_MOOP_PROG-main/products/models.py
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def get_absolute_url(self):
        return f"http://127.0.0.1:8000/product/{self.id}"

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

PycharmProjects/CP_MOOP_PROG-main/products/forms.py
from django import forms
from .models import *


# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]

PycharmProjects/CP_MOOP_PROG-main/products/views.py
from django.shortcuts import render, redirect
from products.models import *
from .decorators import ensure_session_key  # Импортируем декоратор

@ensure_session_key
def product(request, product_id):
    product = Product.objects.get(id=product_id)

    if request.method == 'POST':
        image = request.FILES.get('image')
        if image:
            ProductImage.objects.create(product=product, image=image, is_main=True)
            return redirect(f'http://127.0.0.1:8000/product/{product.id}/')

    print(request.session.session_key)

    return render(request, 'products/product.html', locals())

PycharmProjects/CP_MOOP_PROG-main/templates/products/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Описание
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                Доставка
                            </a>
                        </li>
                          {% if user.is_superuser %}
                          <li role="presentation">
                            <a href="#picture" aria-controls="profile" role="tab" data-toggle="tab">
                                Добавить картинку
                            </a>
                          {% endif %}
                        </li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <h3>Как мы делаем доставку</h3>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="picture">
                            {% if user.is_superuser %}
                            <form method="post" enctype="multipart/form-data">
                              {% csrf_token %}
                              <input type="file" name="image">
                              <button type="submit">Добавить картинку</button>
                            </form>
                            {% endif %}
                        </div>
                      </div>
                </div>
                <div>
                    <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}">{% csrf_token %}
                        <div class="form-group">
                             <input type="number" class="form-control" name="number" id="number">
                        </div>
                            <div class="form-group">
                                <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                    data-product_id = "{{ product.id }}"
                                    data-name ="{{ product.name }}"
                                    data-price ="{{ product.price }}"
                                >
                                    Купить
                                </button>
                            </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}